name: Deploy Translate App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      # Build Frontend (React / Vite)
      - name: Build Frontend
        working-directory: web
        run: |
          npm ci
          npm run build

      # Build Backend
      - name: Build Backend
        working-directory: backend
        run: |
          npm ci
          npm run build

      - name: Deploy Backend build
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY:  ${{ secrets.SSH_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "$SSH_KEY"
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" \
            --exclude "node_modules" --exclude ".git" --exclude .env \
            backend/dist backend/package.json backend/package-lock.json \
            "$SSH_USER@$SSH_HOST:/home/mern/server/"

      - name: Deploy Frontend
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY:  ${{ secrets.SSH_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "$SSH_KEY"
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" \
            web/dist/ "$SSH_USER@$SSH_HOST:/home/mern/client/"

      # Restart API Server
      - name: Restart PM2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{secrets.SSH_USER}}
          key: ${{ secrets.SSH_KEY}}
          script: |
            cd /home/mern/server/dist
            npm ci --omit=dev
            pm2 restart express-api || pm2 start server.js --name express-api
            pm2 save
